### ISSUE TITLE
Train VOC dataset with multi GPU

### ISSUE THREAD

**Issue by DeanDon** [terrychenism/mx-rfcn#7]
`/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:2652: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  VisibleDeprecationWarning)
Traceback (most recent call last):
  File "train_end2end_resnext.py", line 239, in <module>
    main()
  File "train_end2end_resnext.py", line 182, in main
    begin_epoch=args.load_epoch, num_epoch=args.num_epoch)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/module/base_module.py", line 356, in fit
    for_training=True, force_rebind=force_rebind)
  File "/home/gpudouble1/mx-rfcn/rcnn/module.py", line 136, in bind
    force_rebind=False, shared_module=None)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/module/module.py", line 284, in bind
    grad_req=grad_req, input_types=input_types)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/module/executor_group.py", line 187, in __init__
    self.label_layouts = self.decide_slices(label_shapes)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/module/executor_group.py", line 212, in decide_slices
    + ("%s has shape %s" % (name, shape)))
AssertionError: all data must have the same batch size: batch_size = 2, but label has shape (1, 49152)`

I am use multi GPU to train the VOC2007 dataset，and I get this problem.
when I use single GPU to train the same dataset，It's worked.

**Comment by terrychenism** [comment]
Did you use rfcn-rebase branch?

**Comment by DeanDon** [comment]
@terrychenism
Yes，I use rfcn-rebase.
I'm just worried about whether this version supports multiple GPU?

**Comment by PureDiors** [comment]
@DeanDon There is a bug. You can set the inferred shape (1, 49152) to (num_gpus,49152) manually as well as other shapes inferred from assign_anchor() function at https://github.com/terrychenism/mx-rfcn/blob/master/train_end2end_resnext.py#L40.

**Comment by DeanDon** [comment]
@PureDiors
I am change the inferred shape from(1,49152) to (num_gpus,49152) like that:
`    label_shape=(label['label'].shape)[1]
    bbox_target_shape=(label['bbox_target'].shape)[1]
    bbox_inside_weight_shape=(label['bbox_inside_weight'].shape)[1]
    bbox_outside_weight_shape=(label['bbox_outside_weight'].shape)[1]
    max_label_shape = [('label', (num_gpus,label_shape)),
                       ('bbox_target', (num_gpus,bbox_target_shape)),
                       ('bbox_inside_weight', (num_gpus,bbox_inside_weight_shape)),
                       ('bbox_outside_weight', (num_gpus,bbox_outside_weight_shape)),
                       ('gt_boxes', (config.TRAIN.IMS_PER_BATCH, 5*100))]  # assume at most 1200 faces in image`
 And I get this error,maybe I need change the cade in function assign_anchor()?
ERROR like that:
`voc_2007_trainval gt roidb loaded from /home/gpudouble1/mx-rfcn/data/cache/voc_2007_trainval_gt_roidb.pkl
append flipped images to roidb
prepare roidb
/usr/local/lib/python2.7/dist-packages/numpy/core/fromnumeric.py:2652: VisibleDeprecationWarning: `rank` is deprecated; use the `ndim` attribute or function instead. To find the rank of a matrix see `numpy.linalg.matrix_rank`.
  VisibleDeprecationWarning)
infer_shape error. Arguments:
  bbox_target: (1, 48)
  im_info: (1, 3L)
  bbox_inside_weight: (1, 48)
  label: (1, 49152)
  gt_boxes: (1, 500)
  bbox_outside_weight: (1, 48)
  data: (1, 3, 1024, 1024)
Traceback (most recent call last):
  File "train_end2end_resnext.py", line 244, in <module>
    main()
  File "train_end2end_resnext.py", line 187, in main
    begin_epoch=args.load_epoch, num_epoch=args.num_epoch)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/module/base_module.py", line 356, in fit
    for_training=True, force_rebind=force_rebind)
  File "/home/gpudouble1/mx-rfcn/rcnn/module.py", line 136, in bind
    force_rebind=False, shared_module=None)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/module/module.py", line 284, in bind
    grad_req=grad_req, input_types=input_types)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/module/executor_group.py", line 191, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/module/executor_group.py", line 230, in bind_exec
    self.execs.append(self._bind_ith_exec(i, data_shapes, label_shapes, shared_group))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/module/executor_group.py", line 452, in _bind_ith_exec
    arg_shapes, _, aux_shapes = self.symbol.infer_shape(**input_shapes)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/symbol.py", line 459, in infer_shape
    return self._infer_shape_impl(False, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/symbol.py", line 526, in _infer_shape_impl
    ctypes.byref(complete)))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: InferShape Error in _minus0's rhs argument
Shape inconsistent, Provided=(1,48), inferred shape=(1,48,64,64)Corresponding keyword of symbol: bbox_target
Shape inconsistent, Provided=(1,48), inferred shape=(1,48,64,64)`

**Comment by PureDiors** [comment]
@DeanDon Just add one line after https://github.com/terrychenism/mx-rfcn/blob/master/train_end2end_resnext.py#L135
like this:
max_label_shape = [('label', (num_gpus, 49152)), ('bbox_target', (num_gpus, 48, 64, 64)), ('bbox_inside_weight', (num_gpus, 48, 64, 64)), ('bbox_outside_weight', (num_gpus, 48, 64, 64)), ('gt_boxes', (num_gpus, 500))]
to correct the inferred shape. Then it will be OK. Good Luck!

**Comment by DeanDon** [comment]
@PureDiors
It's worked!
Thank you  so much!
